### ISSUE TITLE
Zbay fails to quit on Mac

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#283]
Steps to reproduce:

1. quit zbay

expected: it quits

actual: there is an error message and I don't think it ever quits. 

error (appears the second time you hit CMD-Q)

```
Uncaught Exception:
Error
at process.<anonymous> (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/waggle/lib/libp2p/connectionsManager.js:218:19)
at process.emit (events.js:315:20)
at processEmit (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/signal-exit/index.js:161:32)
at process.emit (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:461:21)
at processPromiseRejections (internal/process/promises.js:245:33)
at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by kingalg** [comment]
I've added information about Windows as there is similar problem caused by the same bug. On Windows it looks like zbay is closed but processes are hanging and zbay can not be open if they are not killed.
