### ISSUE TITLE
glibc not found, 'couldn't install devtools' on Debian 10 AppImage

### ISSUE THREAD

**Issue by BostonZcash** [ZbayApp/ZbayLite#32]
On Debian 10, running the v0.0.4 AppImage results in:
```
$ ./Zbay-lite-0.0.4-zbay-lite-beta.AppImage --no-sandbox
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Zbay-lhmKGnL/resources/worker/index.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Function.Module._load (internal/modules/cjs/loader.js:728:14)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_Zbay-lhmKGnL/resources/worker/RPC.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Function.Module._load (internal/modules/cjs/loader.js:728:14)
Couldn't install devtools.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```
The initial Zbay synchronisation window comes up, though it does not sync past 0 blocks, nor does it retrieve the current block height.

This is reproduceable.

**Comment by holmesworcester** [comment]
@NorbertBodziony can you reproduce this?

**Comment by BostonZcash** [comment]
zbay-lite v2.0.0 resolved this. :+1:
